// Utility for region normalization across countries

const provinceMap = {
    ON: "Ontario",
    Ontario: "Ontario",
    QC: "Quebec",
    Quebec: "Quebec",
    BC: "British Columbia",
    "British Columbia": "British Columbia",
    AB: "Alberta",
    Alberta: "Alberta",
    MB: "Manitoba",
    Manitoba: "Manitoba",
    SK: "Saskatchewan",
    Saskatchewan: "Saskatchewan",
    NL: "Newfoundland and Labrador",
    "Newfoundland and Labrador": "Newfoundland and Labrador",
    NB: "New Brunswick",
    "New Brunswick": "New Brunswick",
    NS: "Nova Scotia",
    "Nova Scotia": "Nova Scotia",
    PE: "Prince Edward Island",
    "Prince Edward Island": "Prince Edward Island",
};
const stateMap = {
    AL: "Alabama",
    Alabama: "Alabama",
    AK: "Alaska",
    Alaska: "Alaska",
    AZ: "Arizona",
    Arizona: "Arizona",
    AR: "Arkansas",
    Arkansas: "Arkansas",
    CA: "California",
    California: "California",
    CO: "Colorado",
    Colorado: "Colorado",
    CT: "Connecticut",
    Connecticut: "Connecticut",
    DE: "Delaware",
    Delaware: "Delaware",
    FL: "Florida",
    Florida: "Florida",
    GA: "Georgia",
    Georgia: "Georgia",
    HI: "Hawaii",
    Hawaii: "Hawaii",
    ID: "Idaho",
    Idaho: "Idaho",
    IL: "Illinois",
    Illinois: "Illinois",
    IN: "Indiana",
    Indiana: "Indiana",
    IA: "Iowa",
    Iowa: "Iowa",
    KS: "Kansas",
    Kansas: "Kansas",
    KY: "Kentucky",
    Kentucky: "Kentucky",
    LA: "Louisiana",
    Louisiana: "Louisiana",
    ME: "Maine",
    Maine: "Maine",
    MD: "Maryland",
    Maryland: "Maryland",
    MA: "Massachusetts",
    Massachusetts: "Massachusetts",
    MI: "Michigan",
    Michigan: "Michigan",
    MN: "Minnesota",
    Minnesota: "Minnesota",
    MS: "Mississippi",
    Mississippi: "Mississippi",
    MO: "Missouri",
    Missouri: "Missouri",
    MT: "Montana",
    Montana: "Montana",
    NE: "Nebraska",
    Nebraska: "Nebraska",
    NV: "Nevada",
    Nevada: "Nevada",
    NH: "New Hampshire",
    "New Hampshire": "New Hampshire",
    NJ: "New Jersey",
    "New Jersey": "New Jersey",
    NM: "New Mexico",
    "New Mexico": "New Mexico",
    NY: "New York",
    "New York": "New York",
    NC: "North Carolina",
    "North Carolina": "North Carolina",
    ND: "North Dakota",
    "North Dakota": "North Dakota",
    OH: "Ohio",
    Ohio: "Ohio",
    OK: "Oklahoma",
    Oklahoma: "Oklahoma",
    OR: "Oregon",
    Oregon: "Oregon",
    PA: "Pennsylvania",
    Pennsylvania: "Pennsylvania",
    RI: "Rhode Island",
    "Rhode Island": "Rhode Island",
    SC: "South Carolina",
    "South Carolina": "South Carolina",
    SD: "South Dakota",
    "South Dakota": "South Dakota",
    TN: "Tennessee",
    Tennessee: "Tennessee",
    TX: "Texas",
    Texas: "Texas",
    UT: "Utah",
    Utah: "Utah",
    VT: "Vermont",
    Vermont: "Vermont",
    VA: "Virginia",
    Virginia: "Virginia",
    WA: "Washington",
    Washington: "Washington",
    WV: "West Virginia",
    "West Virginia": "West Virginia",
    WI: "Wisconsin",
    Wisconsin: "Wisconsin",
    WY: "Wyoming",
    Wyoming: "Wyoming",
};
const ukRegionMap = {
    ENG: "England",
    England: "England",
    SCT: "Scotland",
    Scotland: "Scotland",
    WLS: "Wales",
    Wales: "Wales",
    NIR: "Northern Ireland",
    "Northern Ireland": "Northern Ireland",
};

function normalizeRegion(region, country) {
    if (!region) return "";
    if (/canada/i.test(country)) return provinceMap[region] || region;
    if (/usa|united states/i.test(country)) return stateMap[region] || region;
    if (/uk|united kingdom/i.test(country))
        return ukRegionMap[region] || region;
    return region;
}

module.exports = {
    provinceMap,
    stateMap,
    ukRegionMap,
    normalizeRegion,
};
